import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './creative-rooms.css'
import './vector-broadcast.css'
import './broadcast-control.css'
import './premium-office.css'
import './office-v2.css'
import './diorama-office.css'
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
